### ISSUE TITLE
Replay displaying cards etc. incorrectly, bug?

### ISSUE THREAD

**Issue by HHH-Fan** [HearthSim/Joust#212] opened 2018-01-28 00:47 UTC
https://hsreplay.net/replay/gdcKptxsGo2VsKjjG3RhNm

Replay doesn't load first, when accessing Fullscreen it works but without displaying the cards, minions etc. correctly. I deactivated ublock and restarted firefox, didn't help.

![image](https://user-images.githubusercontent.com/235410/35477921-d3acf0b0-03d7-11e8-987a-ab28480af69c.png)

Just installed the new Decktracker version 3 days or so ago. Worked fine then.
Ideas what I would have to do to fix this problem?

**Comment by jleclanche** [comment] 2018-01-28 01:05
At a glance, you're probably having issues loading api.hearthstonejson.com and/or art.hearthstonejson.com. Check network log or try a different browser; this is usually caused by adblocker / privacy extensions.

Closing since this isn't a joust bug but feel free to reply if you need more help.

**Closed by jleclanche** 2018-01-28 01:05 UTC

**Comment by HHH-Fan** [comment] 2018-01-28 01:17
Thx for the fast reply.
Sorry, I'm a absolute computer fool. Network log means checking something at the Decktracker directly or checking something at firefox ?
I haven't changed anything since the day the Decktracker worked.
I'll try out another browser though I hope I can get back to use it on firefox.

**Comment by jleclanche** [comment] 2018-01-28 01:33
@HHH-Fan In short, this is likely caused by either an extension in your browser, an overeager firewall, or a problem with your ISP.

A better place for support is our Discord server: https://discord.gg/hearthsim

**Comment by HHH-Fan** [comment] 2018-01-28 01:37
Okay, thanks.
