### ISSUE TITLE
Allow Replay playback to be paused and/or stepped forward manually

### ISSUE THREAD

**Issue by smallnamespace** [HearthSim/joust#3] opened 2016-01-08 23:57 UTC
Allow Replay playback to be paused and/or stepped forward manually:

Basically some actions are a bit complicated and it's easy to miss what happened, so it would be nice to be able to pause.

**Comment by smallnamespace** [comment] 2016-01-08 23:57
I'm willing to work on this myself, but I need to get up to speed on reading React code

**Comment by beheh** [comment] 2016-02-04 21:34
Duplicate of #4.

**Closed by beheh** 2016-02-04 21:34 UTC
Labels: feature, hsreplay
