### ISSUE TITLE
Scrubbing slow on some games

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Joust#171] opened 2016-10-21 08:38 UTC
https://hsreplay.net/replay/vmPr4AFbMBmq7W3M5CKn6f ShiftCon Brawl game

Something to do with shifter zerus? I removed the .shifting css rule and it still was happening so I don't think that's it.

**Comment by beheh** [comment] 2016-10-21 08:52
I can't reproduce that in Chromium here, Firefox is hard to tell since it's always pretty slow. Scrubbing is comparably fast to the [featured game](https://hsreplay.net/replay/vZEz7JoNnfgVo34HJUHhEF). Could you describe the issue a bit more?

**Comment by jleclanche** [comment] 2016-10-21 09:03
It's still smooth but noticeably slower. My CPU spins up quite a bit when I scroll back and forth a lot. Probably just worth doing some profiling.

**Comment by beheh** [comment] 2016-12-13 12:16
We can do some in-depth profiling at some point to improve the general Joust performance, but I can't reproduce this specific issue. Closing.

**Closed by beheh** 2016-12-13 12:16 UTC
